<a href="https://colab.research.google.com/github/hanifaekafauziah/PM-Turi2-Preprocessing-HanifaEkaFauziah/blob/main/PM_P4_HanifaEkaFauziah_2488010060.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Langkah Praktikum**

In [3]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

Langkah 1 — Menangani nilai hilang (imputasi median/modus).

In [4]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

Langkah 2 — Memisahkan fitur (X) dan label (y).

In [5]:
X = df.drop(columns=['membeli'])
y = df['membeli']

Langkah 3 — Encoding kategorikal (ordinal & one-hot).

In [6]:
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})

Langkah 4 — Membagi data (SEBELUM scaling).

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)

Langkah 5 — Penskalaan (fit pada latih, transform pada latih & uji).

In [8]:
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num]) # cegah data leakage

Langkah 6 — Verifikasi: tidak ada nilai hilang, semua numerik, skala seragam.

In [9]:
# Cek apakah masih ada nilai yang hilang
print("Jumlah nilai hilang:")
print(X_train.isnull().sum())
print()

# Cek tipe data setiap kolom
print("Tipe data:")
print(X_train.dtypes)
print()

# Melihat statistik data setelah scaling
print("Statistik data setelah scaling:")
print(X_train.describe())

Jumlah nilai hilang:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Tipe data:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

Statistik data setelah scaling:
               usia    pendapatan    pendidikan  kota_Bandung  kota_Jakarta  \
count  7.000000e+00  7.000000e+00  7.000000e+00      7.000000      7.000000
mean   1.110223e-16  1.030921e-16 -1.982541e-17      0.428571      0.428571
std    1.080123e+00  1.080123e+00  1.080123e+00      0.534522      0.534522
min   -1.588665e+00 -1.169416e+00 -1.028992e+00      0.000000      0.000000
25%   -5.847169e-01 -8.023348e-01 -1.028992e+00      0.000000      0.000000
50%   -4.412958e-02 -3.251291e-01  1.714986e-01      0.000000      0.000000
75%    6.509113e-01  6.659903e-01  7.717436e-01      1.000000      1.000000
max    1.500406e+00  1.767234e+00  1.371989e+00      1.000000      1.000000

       kota_Surabaya
count       7.000000
mean        0.142857
std         0.377964
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [10]:
df_median = df.copy()

**Latihan Mandiri**

1. Ganti imputasi usia menjadi mean; bandingkan hasilnya.

In [11]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

print("Mean Usia:", df_median ['usia'].median())
print("Mean Pendapatan:", df_median ['pendapatan'].median())
print(display(df_median))

Mean Usia: 35.0
Mean Pendapatan: 7500000.0

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

None

In [12]:
df['usia'] = df['usia'].fillna(df['usia'].mean())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].mean())

print("Mean Usia:", df['usia'].mean())
print("Mean Pendapatan:", df['pendapatan'].mean())
print(display(df))

Mean Usia: 35.9
Mean Pendapatan: 8030000.0

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

None

In [13]:
print("Median:", df['usia'].median())
print("Mean:", df['usia'].mean())

Median: 35.0
Mean: 35.9

2. Gunakan MinMaxScaler (0–1) sebagai ganti StandardScaler; tampilkan describe().

In [14]:
from sklearn.preprocessing import MinMaxScaler
num = ['usia','pendapatan','pendidikan']
sc = MinMaxScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])

X_train[num].describe()

           usia  pendapatan  pendidikan
count  7.000000    7.000000    7.000000
mean   0.514286    0.398214    0.428571
std    0.349660    0.367808    0.449868
min    0.000000    0.000000    0.000000
25%    0.325000    0.125000    0.000000
50%    0.500000    0.287500    0.500000
75%    0.725000    0.625000    0.750000
max    1.000000    1.000000    1.000000

3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding.

In [15]:
X['departemen'] = ['HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'HR', 'Finance', 'IT']
X = pd.get_dummies(X, columns=['departemen'], dtype=int)

X.head()

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya,departemen_Finance,departemen_HR,departemen_IT
0,25.0,4000000.0,0,1,0,0,0,1,0
1,32.0,7500000.0,1,0,1,0,0,0,1
2,35.0,5200000.0,0,1,0,0,1,0,0
3,45.0,12000000.0,2,0,0,1,0,0,1
4,28.0,4800000.0,0,0,1,0,0,1,0

4. Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji.

Karena scaler harus belajar dari data latih saja agar tidak terjadi data leakage. Data uji tidak ikut serta untuk menentukan rata-rata standar deviasi, nilai minimum/maksimum. Jadi data uji tetap menjadi data yang benar-benar "baru" untuk menguji model.

**E. Refleksi**

1. Mengapa urutan 'split dulu, baru scaling' penting?

Karena Urutan tersebut penting agar data uji tidak ikut memengaruhi proses scaling pada data latih. Jika scaling dilakukan sebelum data dibagi, informasi dari data uji dapat ikut digunakan dalam perhitungan nilai seperti mean dan standar deviasi. Hal ini disebut data leakage dan dapat membuat hasil evaluasi model menjadi kurang objektif. Oleh karena itu, data dibagi terlebih dahulu, kemudian scaling dilakukan berdasarkan data latih dan diterapkan pada data uji.

2. Kapan label encoding dan kapan one-hot encoding?

Label encoding digunakan ketika kategori memiliki urutan atau tingkatan tertentu, misalnya rendah, sedang, tinggi atau untuk mengubah label target seperti Lulus dan Tidak Lulus menjadi angka. Sedangkan one-hot encoding digunakan untuk data kategori yang tidak memiliki urutan, misalnya Jawa Barat, Jawa Tengah, Jawa Timur. Setiap kategori dibuat menjadi kolom tersendiri dengan nilai 0 atau 1 sehingga model tidak menganggap ada hubungan tingkatan antar kategori.

3. Apa perbedaan normalisasi dan standardisasi?

Normalisasi mengubah nilai data ke rentang tertentu, biasanya 0 sampai 1, sehingga skala setiap fitur menjadi lebih seragam. Sementara standardisasi mengubah data berdasarkan rata-rata (mean) dan standar deviasi sehingga data memiliki mean 0 dan standar deviasi 1. Normalisasi cocok ketika ingin membatasi nilai pada rentang tertentu, sedangkan standardisasi sering digunakan ketika model membutuhkan data dengan skala yang berpusat di sekitar nol.